# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Permalinks
permalink:           pretty

# Setup
title:               intermediate_ruby
tagline:             "Deliver More Value"
title_image:         "/images/site_base_image.jpg"
url:                 https://intermediateruby.com/
baseurl:             ""

# paginate:            5
excerpt_separator:   <!--more-->
future: true
twitter_username:   "josh_works"

# pages in nav bar
include: ['_pages']

# pages across header
# seems to need `jekyll build` to catch updates on localhost
pages_list:
  about: '/about'

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josh Thompson
  url:               https://twitter.com/josh_works
  email:             joshthompson@hey.com

# Custom vars
github:
  repo:              https://github.com/josh-works/intermediaterubycom

  # twitter plugin gem
plugins:
  - jekyll-twitter-plugin
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  # syntax_highlighter: rouge
